// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "myImage":return img`
................................
................................
................................
................................
..........ffffffff..............
........ffffffffffff............
.......ffffffffffffff...........
.......ffffffffffffff...........
.......ffffffffffffff...........
.......ffffffffffffff...........
.......fff77777f77fff...........
.......ff7777777777ff...........
.......ff7777777777ff...........
.......ff7777777777ff...........
.......ff7777777777ff...........
.......ff7777777777ff...........
.......ff7777e7e777ff...........
.......ff7f7ee7e7f7ff...........
.......ff7f7eeee7f7ff...........
.......ff7ffeeee7f7ff...........
.......fffffeeee7f7ff...........
.......fffffeeeefffff...........
.......ffffeeeeeeffff...........
.......ffffffffffffff...........
.......ffffffffffffff...........
.......ffffffffffffff...........
.......ffffffffffffff...........
.......ffffffffffffff...........
................................
................................
................................
................................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
